---
- name: Switch CPU governor to performance
  block:
    - name: Install cpufrequtils for CPU frequency management
      package:
        name: cpufrequtils
        state: present

    - name: Set CPU governor to performance
      shell: |
        for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
          echo performance > $cpu || true
        done
      args:
        executable: /bin/bash
      changed_when: false

  rescue:
    - debug:
        msg: "Failed to set CPU governor to performance."